config/routes.rb
# == Route Map
#
#                                   Prefix Verb URI Pattern                                                                                       Controller#Action
#                       rails_health_check GET  /up(.:format)                                                                                     rails/health#show
#                              sidekiq_web      /sidekiq                                                                                          Sidekiq::Web
#                                 lookbook      /lookbook                                                                                         Lookbook::Engine
#                                   clicks GET  /clicks(.:format)                                                                                 clicks#index
#                                          POST /clicks(.:format)                                                                                 clicks#create
#                              webmanifest GET  /manifest.v1.webmanifest(.:format)                                                                statics#manifest
#                                    about GET  /about(.:format)                                                                                  about#index
#                                     root GET  /                                                                                                 clicks#index
#         turbo_recede_historical_location GET  /recede_historical_location(.:format)                                                             turbo/native/navigation#recede
#         turbo_resume_historical_location GET  /resume_historical_location(.:format)                                                             turbo/native/navigation#resume
#        turbo_refresh_historical_location GET  /refresh_historical_location(.:format)                                                            turbo/native/navigation#refresh
#            rails_postmark_inbound_emails POST /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET  /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET  /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET  /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#            rails_conductor_inbound_email GET  /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
# new_rails_conductor_inbound_email_source GET  /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
#    rails_conductor_inbound_email_sources POST /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
#    rails_conductor_inbound_email_reroute POST /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
# rails_conductor_inbound_email_incinerate POST /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)                            rails/conductor/action_mailbox/incinerates#create
#                       rails_service_blob GET  /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#                 rails_service_blob_proxy GET  /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                          GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#                rails_blob_representation GET  /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
#          rails_blob_representation_proxy GET  /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                          GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#                       rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#                update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#                     rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create
#
# Routes for Lookbook::Engine:
#         lookbook_home GET  /                        lookbook/application#index
#   lookbook_page_index GET  /pages(.:format)         lookbook/pages#index
#         lookbook_page GET  /pages/*path(.:format)   lookbook/pages#show
#     lookbook_previews GET  /previews(.:format)      lookbook/previews#index
#      lookbook_preview GET  /preview/*path(.:format) lookbook/previews#show
#      lookbook_inspect GET  /inspect/*path(.:format) lookbook/inspector#show
# lookbook_embed_lookup GET  /embed(.:format)         lookbook/embeds#lookup
#        lookbook_embed GET  /embed/*path(.:format)   lookbook/embeds#show
#                       GET  /*path(.:format)         lookbook/application#not_found

require 'sidekiq/web'
require 'lockup'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  mount Lockup::Engine, at: '/lockup' if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?

  if Rails.configuration.x.cypress
    namespace :cypress do
      delete 'cleanup', to: 'cleanup#destroy'
    end
  end

  resources :clicks, only: %i[index create]

  get '/manifest.v1.webmanifest', to: 'statics#manifest', as: :webmanifest
  get '/about', to: 'about#index', as: :about

  root to: 'clicks#index'
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    = tag.meta charset: 'utf-8'
    = tag.title 'Templatus-Hotwire'

    = tag.meta content: 'Ruby on Rails template for using Hotwire', name: 'description'
    = tag.meta content: 'width=device-width,initial-scale=1', name: 'viewport'
    = tag.meta content: 'yes', name: 'mobile-web-app-capable'
    = tag.meta content: 'Templatus (Hotwire edition)', name: 'application-name'
    = tag.meta content: '#991c1c', name: 'theme-color'
    = tag.meta content: '#ffc40d', name: 'msapplication-TileColor'
    = tag.meta content: 'yes', name: 'apple-mobile-web-app-capable'
    = tag.meta content: 'Templatus (Hotwire edition)', name: 'apple-mobile-web-app-title'
    = tag.meta content: 'black', name: 'apple-mobile-web-app-status-bar-style'
    = tag.meta content: Rails.configuration.x.git.commit_version, name: 'git-commit-version'
    = tag.meta content: Rails.configuration.x.git.commit_time, name: 'git-commit-time'
    - if Rails.configuration.x.honeybadger.api_key
      = tag.meta content: Rails.configuration.x.honeybadger.api_key, name: 'honeybadger-api-key'
    - if Rails.configuration.x.app_host
      = tag.meta name: 'app-host', content: Rails.configuration.x.app_host
    - if Rails.configuration.x.plausible_url
      = tag.meta name: 'plausible-url', content: Rails.configuration.x.plausible_url

    = csrf_meta_tags
    = action_cable_meta_tag

    = tag.link href: asset_path('/apple-touch-icon.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180'
    = tag.link href: asset_path('/favicon-32x32.png'),    rel: 'icon',             type: 'image/png', sizes: '32x32'
    = tag.link href: asset_path('/favicon-16x16.png'),    rel: 'icon',             type: 'image/png', sizes: '16x16'
    = tag.link href: asset_path('/safari-pinned-tab.svg'),rel: 'mask-icon',        color: '#d30001'
    = tag.link href: webmanifest_path, rel: 'manifest'
    = tag.link href: vite_asset_path('images/logo.svg'), rel: 'preload', as: 'image'

    = vite_client_tag
    = vite_typescript_tag 'application', 'data-turbo-track': 'reload'
    = vite_stylesheet_tag 'application', 'data-turbo-track': 'reload'

  %body
    .flex.flex-col.min-h-screen.bg-gradient-to-br.from-primary.to-secondary.lg:bg-tertiary.lg:from-inherit.lg:to-inherit
      = render AppBackground::Component.new
      = render AppHeader::Component.new class: 'lg:fixed lg:top-10 lg:left-10'

      = turbo_frame_tag 'flash' do
        - if flash.present?
          = render AppFlash::Component.new(notice:, alert:)

      %main.relative.flex-1.px-4.py-5.bg-white.shadow-md.sm:px-6.lg:px-8.lg:mt-10.lg:mr-16.lg:ml-96.lg:max-w-5xl.lg:rounded-xl
        = yield

      = render AppFooter::Component.new class: 'relative mt-2 mb-6 lg:px-0 lg:mr-16 lg:ml-96 lg:max-w-5xl'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    = tag.meta charset: 'utf-8'

    = tag.title 'Templatus-Hotwire'

    = tag.meta content: 'Ruby on Rails template for using Hotwire', name: 'description'
    = tag.meta content: 'width=device-width,initial-scale=1', name: 'viewport'
    = tag.meta content: 'yes', name: 'mobile-web-app-capable'
    = tag.meta content: 'Templatus (Hotwire edition)', name: 'application-name'
    = tag.meta content: '#991c1c', name: 'theme-color'
    = tag.meta content: '#ffc40d', name: 'msapplication-TileColor'
    = tag.meta content: 'yes', name: 'apple-mobile-web-app-capable'
    = tag.meta content: 'Templatus (Hotwire edition)', name: 'apple-mobile-web-app-title'
    = tag.meta content: 'black', name: 'apple-mobile-web-app-status-bar-style'
    = tag.meta content: Rails.configuration.x.git.commit_version, name: 'git-commit-version'
    = tag.meta content: Rails.configuration.x.git.commit_time, name: 'git-commit-time'

    - if Rails.configuration.x.honeybadger.api_key
      = tag.meta content: Rails.configuration.x.honeybadger.api_key, name: 'honeybadger-api-key'

    - if Rails.configuration.x.app_host
      = tag.meta name: 'app-host', content: Rails.configuration.x.app_host
    - if Rails.configuration.x.plausible_url
      = tag.meta name: 'plausible-url', content: Rails.configuration.x.plausible_url

    = csrf_meta_tags
    = action_cable_meta_tag

    = tag.link href: asset_path('/apple-touch-icon.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180'
    = tag.link href: asset_path('/favicon-32x32.png'),    rel: 'icon',             type: 'image/png', sizes: '32x32'
    = tag.link href: asset_path('/favicon-16x16.png'),    rel: 'icon',             type: 'image/png', sizes: '16x16'
    = tag.link href: asset_path('/safari-pinned-tab.svg'),rel: 'mask-icon',        color: '#d30001'
    = tag.link href: webmanifest_path, rel: 'manifest'
    = tag.link href: vite_asset_path('images/logo.svg'), rel: 'preload', as: 'image'

    = vite_client_tag
    = vite_typescript_tag 'application', 'data-turbo-track': 'reload'
    = vite_stylesheet_tag 'application', 'data-turbo-track': 'reload'

  body
    div class="flex flex-col min-h-screen bg-gradient-to-br from-primary to-secondary lg:bg-tertiary lg:from-inherit lg:to-inherit"
      = render AppBackground::Component.new

      = render AppHeader::Component.new class: 'lg:fixed lg:top-10 lg:left-10'

      = turbo_frame_tag 'flash' do
        - if flash.present?
          = render AppFlash::Component.new(notice:, alert:)

      main class="relative flex-1 px-4 py-5 bg-white shadow-md sm:px-6 lg:px-8 lg:mt-10 lg:mr-16 lg:ml-96 lg:max-w-5xl lg:rounded-xl"
        = yield

      = render AppFooter::Component.new class: 'relative mt-2 mb-6 lg:px-0 lg:mr-16 lg:ml-96 lg:max-w-5xl'

app/views/layouts/preview.html.haml
!!! 5
%html
  %head
    %meta{name: 'viewport', content: 'width=device-width,initial-scale=1'}/

    %title Component Preview

    = vite_client_tag
    = vite_typescript_tag 'application', 'data-turbo-track': 'reload'
    = vite_stylesheet_tag 'application', 'data-turbo-track': 'reload'

  %body
    .p-4
      = yield

app/views/layouts/preview.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width,initial-scale=1"
    title Component Preview
    = vite_client_tag
    = vite_typescript_tag 'application', 'data-turbo-track': 'reload'
    = vite_stylesheet_tag 'application', 'data-turbo-track': 'reload'

  body
    div class="p-4"
      = yield